name: Build WaveScope (AU & VST3)

on:
  workflow_dispatch:
  push:
    branches: [ main, master ]

env:
  SRC_DIR: WaveScope_FetchJUCE
  BUILD_DIR: WaveScope_FetchJUCE/build

jobs:
  build-macos:
    runs-on: macos-14
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Ensure cmake
        run: |
          brew update
          brew install cmake || true

      - name: Configure (CMake -> Xcode)
        run: |
          cmake -S "$SRC_DIR" -B "$BUILD_DIR" -G Xcode -D CMAKE_OSX_ARCHITECTURES="arm64;x86_64"

      - name: Build Release
        run: |
          cmake --build "$BUILD_DIR" --config Release

      - name: Locate plugs
        id: locate
        run: |
          set -e
          AU=""
          VST3=""
          if [ -d "$BUILD_DIR/Release/WaveScope.component" ]; then AU="$BUILD_DIR/Release/WaveScope.component"; fi
          if [ -z "$AU" ] && [ -d "$BUILD_DIR/WaveScope_artefacts/Release/AU/WaveScope.component" ]; then AU="$BUILD_DIR/WaveScope_artefacts/Release/AU/WaveScope.component"; fi
          if [ -d "$BUILD_DIR/Release/WaveScope.vst3" ]; then VST3="$BUILD_DIR/Release/WaveScope.vst3"; fi
          if [ -z "$VST3" ] && [ -d "$BUILD_DIR/WaveScope_artefacts/Release/VST3/WaveScope.vst3" ]; then VST3="$BUILD_DIR/WaveScope_artefacts/Release/VST3/WaveScope.vst3"; fi
          echo "au_path=$AU"   >> $GITHUB_OUTPUT
          echo "vst3_path=$VST3" >> $GITHUB_OUTPUT

      - name: Ad-hoc codesign (AU & VST3)
        run: |
          set -e
          if [ -n "${{ steps.locate.outputs.au_path }}" ]; then
            codesign --force --deep --sign - "${{ steps.locate.outputs.au_path }}"
          fi
          if [ -n "${{ steps.locate.outputs.vst3_path }}" ]; then
            codesign --force --deep --sign - "${{ steps.locate.outputs.vst3_path }}"
          fi
          if [ -n "${{ steps.locate.outputs.au_path }}" ]; then
            codesign -dv --verbose=2 "${{ steps.locate.outputs.au_path }}" || true
          fi
          if [ -n "${{ steps.locate.outputs.vst3_path }}" ]; then
            codesign -dv --verbose=2 "${{ steps.locate.outputs.vst3_path }}" || true
          fi

      - name: Package artifacts
        run: |
          mkdir -p "$SRC_DIR/out"
          if [ -n "${{ steps.locate.outputs.au_path }}" ]; then
            ditto -c -k --sequesterRsrc --keepParent "${{ steps.locate.outputs.au_path }}" "$SRC_DIR/out/WaveScope-AU.zip"
          fi
          if [ -n "${{ steps.locate.outputs.vst3_path }}" ]; then
            ditto -c -k --sequesterRsrc --keepParent "${{ steps.locate.outputs.vst3_path }}" "$SRC_DIR/out/WaveScope-VST3.zip"
          fi

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: WaveScope-binaries
          path: ${{ env.SRC_DIR }}/out/*
